#!/bin/bash

# Just a small cripts that uses 'exiftool' to look at the metadata and renames the files in
# the format: 'Author - Title.pdf'
# Omits renaming files that already have proper title and the ones that don't
# have both the author and title in their metadata

#ECHO color helpers
RED='\033[1;31m'
DRED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

for filename in $1/*.pdf
do

    dir=$(dirname -- "$filename")
    author=$(exiftool -s -s -s -author "$filename")
    title=$(exiftool -s -s -s -title "$filename")
    newName="$author - $title.pdf" 
    if [[ "$(basename "$filename")" == "$newName" ]]
    then
        echo -e "${YELLOW}$(basename "$filename")${NC} ${GREEN}The file is already properly named!${NC}"
    else
        if [[ -z "$author" || -z "$title"  ]]
        then
            echo -e "${DRED}$(basename "$filename")${NC} ${RED}ERROR! MISSING METADATA! OMITTING RENAME${NC}"
        else
            mv "$filename" "$dir/$newName"
            echo -e "Renamed ${YELLOW}$(basename "$filename")${NC} ==> ${GREEN}$newName${NC}"
        fi
    fi
done
